### ISSUE TITLE
bitsandbytes

### ISSUE THREAD

**Issue by al-swaiti** [HighCWu/flux-4bit#2]
hi 
nice code 
,, could i apply this

```
from transformers import BitsAndBytesConfig

double_quant_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
)
```
to this code ,  and will be big step if this code save the model to work with comfyui and stablewebui

**Comment by HighCWu** [comment]
yes, you could use this to quantize flux transformer 2d model with my `model.py` patch. What I provided in huggingface model are quantized weights

**Comment by al-swaiti** [comment]
okay but the output is diffusers not normal safetensores for comfyui

**Comment by HighCWu** [comment]
> okay but the output is diffusers not normal safetensores for comfyui

This is normal behavior, because this project is based on diffusers.

**Comment by al-swaiti** [comment]
its long way ,, to make a node to use this in comfyui using diffusers , could you please guide me to re save the quantized model without diffusers conversion to use in comfyui  , is this the same way here https://huggingface.co/lllyasviel/flux1-dev-bnb-nf4 , also what do u think of this way `quantize_(transformer, int8_weight_only())` its new https://github.com/pytorch/ao

**Comment by al-swaiti** [comment]
plus it will be amazing if you share how to train lora using this model

**Comment by HighCWu** [comment]
you may want to use https://github.com/bghira/SimpleTuner to train lora in low bits which is not base on diffusers. My repo code is not very user friendly to the community😂, it's almost a idea share

**Comment by al-swaiti** [comment]
it could be used but theres , model mmmmmm , i have this idea you can git clone the diffusers  edit t5encoder  & transformer (replace your model.py and import libraries to FluxPipeline )  and make  full repo ...  i'll try to make setup and see you later

**Comment by al-swaiti** [comment]
still here

**Comment by al-swaiti** [comment]
![image](https://github.com/user-attachments/assets/467299e4-e926-4562-a3d8-d474a276af2a)

**Comment by al-swaiti** [comment]
![image](https://github.com/user-attachments/assets/8d212890-3ae8-4ab0-93d1-344ac5eb9652)

**Comment by al-swaiti** [comment]
and paste model.py  there to import those library

**Comment by al-swaiti** [comment]
![image](https://github.com/user-attachments/assets/5c38fd92-5e88-499c-abe6-fecd3ddc0133)

**Comment by al-swaiti** [comment]
have this error 
![image](https://github.com/user-attachments/assets/4368655a-58ae-4fe7-af32-f8a52c4f10a8)
and the code back to original one again!
.... whatever if u clone diffusers and edit the original classess  T5EncoderModel, FluxTransformer2DModel   will be better  , another option could edit simple tuner code 
![image](https://github.com/user-attachments/assets/35fce23f-f4d2-435c-9596-a64d8853a9d8)

**Comment by HighCWu** [comment]
The diffusers pipeline does not currently support loading quantized models, so you need to manually load the quantized model first and then use it as the initialization parameter of the pipeline.
